DROP PACKAGE pck_enerko_reports2_test;
DROP FUNCTION f_arg_resolver_test_no_args;
DROP PROCEDURE p_arg_resolver_test_no_args;
DROP FUNCTION f_arg_resolver_test_some_args;
DROP PROCEDURE p_arg_resolver_test_some_args;